{{- define "niomon-decoder.env" -}}
- name: KAFKA_TOPIC_IN
  value: "ubirch-niomon-req-authorized-bin"
- name: KAFKA_TOPIC_OUT_VALID
  value: "ubirch-niomon-msg-decoded-json"
- name: KAFKA_TOPIC_OUT_INVALID
  value: "ubirch-niomon-error-json"
{{- end -}}

{{- $deployment := (dict "envStr" (include "niomon-decoder.env" .)) -}}

{{- $_ := set $deployment "Root" . -}}
{{- $_ := set $deployment "name" "decoder" -}}
  {{- $_ := set $deployment "replicas" .Values.decoder.replicas -}}

{{ template "niomon.deployment" $deployment }}

---

{{ template "niomon.service" $deployment }}

---

{{ template "niomon.prometheus.monitor" $deployment}}
